# Generated by Django 4.2.5 on 2024-01-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_incomesource_alter_income_source_delete_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='IncomeSource',
        ),
    ]
